[config]
reload_apps = true
# This prefix is used in templates (e.g., {{colors.primary.default.hex}})
prefix = "@"

[templates.kitty]
input_path = '~/dotfiles_sway/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.cache/matugen/kitty-colors.conf'

[templates.waybar]
input_path = '~/dotfiles_sway/.config/matugen/templates/waybar-colors.css'
output_path = '~/.cache/matugen/waybar-colors.css'

[templates.fuzzel]
input_path = '~/dotfiles_sway/.config/matugen/templates/fuzzel-colors.ini'
output_path = '~/.cache/matugen/fuzzel-colors.ini'

[templates.mako]
input_path = '~/dotfiles_sway/.config/matugen/templates/mako-colors.conf'
output_path = '~/dotfiles_sway/.config/mako/config'

[templates.nvim]
input_path = '~/dotfiles_sway/.config/matugen/templates/nvim.lua'
output_path = '~/dotfiles_sway/.config/nvim/lua/colors/matugen.lua'

